on:
  workflow_dispatch:
  schedule:
    # Runs every at midnight
    - cron: '0 0 * * *'
jobs:
  herdstat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: herdstat/herdstat-action@v0.8.0
        with:
          version: v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.ET_HERDSTAT_PAT }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'contribution-graph.svg'
          message: 'Update contribution graph'
